language: python
sudo: true
python:
  - "2.7"
# command to install dependencies
env:
  - PATH
before_install:
  - travis_retry sudo apt-get install rpmbuild
install: "pip install -r imagegw/requirements.txt"
# command to run tests
before_script:
  - export PATH=$PWD/imagegw/test/:$PATH
  - cp imagegw/test.json.example imagegw/test.json
  - mkdir /tmp/imagegw /tmp/systema /tmp/systemb
  - rm imagegw/test/sha256sum
  - touch imagegw/shifter_imagegw/__init__.py
script: cd imagegw/ && export PYTHONPATH=`pwd` && nosetests -x -s
services:
  - mongodb
  - redis
after_failure:
  - find /tmp/
  - cat /tmp/worker.log
notifications:
  slack: shifter-hpc:G2yziADLjfv5y0KoCVT907cS
