language: python
sudo: true
python:
  - "2.7"
# command to install dependencies
env:
  - PATH
before_install:
  - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ precise universe multiverse"
  - sudo add-apt-repository -y ppa:ondrej/php5
  - sudo apt-get update -qq
  - sudo apt-get install -qq libjson-c2 libjson-c-dev libmunge2 libmunge-dev libcurl4-openssl-dev autoconf automake libtool curl make valgrind xfsprogs squashfs-tools
  - sudo pip install cpp-coveralls
install: "pip install -r imagegw/requirements.txt"
# command to run tests
before_script:
  - cp imagegw/test.json.example imagegw/test.json
  - mkdir /tmp/imagegw /tmp/systema /tmp/systemb
  - rm imagegw/test/sha256sum
  - find /tmp/
script:
  - export PROC_COUNT=$(cat /proc/cpuinfo  | egrep '^processor' | wc -l)
  - echo "have $PROC_COUNT processors"
  - ./autogen.sh
  - ./configure --prefix=/usr --sysconfdir=/etc/shifter
  - MAKEFLAGS="-j$PROC_COUNT" make
  - MAKEFLAGS="-j$PROC_COUNT" make check
  - sudo make install 
  - cd src/test
  - ../../extra/CI/test_script.sh
  - cd ../../imagegw
  - export PATH=$PWD/test:$PATH
  - nosetests -x -s
  - cd ..
services:
  - mongodb
  - redis
after_failure:
  - df /tmp
  - find /tmp/
  - ls -latrh /tmp/*
  - ls -latrh /tmp/imagegw/*
  - ls -latrh /tmp/systema/images/*
  - cat /tmp/worker.log
after_success:
  - coveralls --exclude dep -n 
notifications:
  slack: shifter-hpc:G2yziADLjfv5y0KoCVT907cS
