api:
  image: imagegwapi
  ports:
   - 5555:5000
  links:
   - mongo
   - redis
  volumes:
   - /imagegw:/data
   - ./test/config:/config
  command: munge:systema:munge munge:systemb:munge api
mongo:
  image: mongo:2.6
  volumes:
    - /data/db
  command: --smallfiles
redis:
  image: redis
  volumes:
   - ./test/config:/config
  command: redis-server /config/redis.conf
systema:
  container_name: systema
  image: shifter-test
  links:
   - api
  ports:
   - "2222:22"
  volumes:
  - /images
  - ./test/config/:/config
  privileged: true
  environment:
  - ADDUSER=canon
workera:
  image: imagegwapi
  links:
   - api
   - redis
   - systema:systema
  volumes:
   - /imagegw:/data
   - ./test/config/:/config
  command: worker:systema
#workerb:
#  image: imagegwapi
#  links:
#   - api
#   - redis
#  volumes:
#   - /imagegw:/data
#   - ./test/config/:/config
#  command: worker:systemb
#flower:
#  image: imagegwapi
#  links:
#   - redis
#  ports:
#   - 5556:5555
#  command: flower
